version: '3'

services:
  nextjs:
    container_name: dashboard-fe-nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
